###
# This is the place to override the uwsgi cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "uwsgi/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###

# The following shows how to set uwsgi processes number:
#
#normal[:uwsgi][:processes] = 4