###
# This is the place to override the web2py cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "web2py/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###

# The following shows how to disable NGinx compression:
#
#normal[:web2py][:gzip] = 'off'
#normal[:web2py][:gzip_static] = 'off'
